# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = 'white'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = 'darkgreen'

# Limit fullscreen to the browser window (does not expand to fill the
# screen).
# Type: Bool
c.content.windowed_fullscreen = False

# Editor (and arguments) to use for the `open-editor` command. The
# following placeholders are defined: * `{file}`: Filename of the file
# to be edited. * `{line}`: Line in which the caret is found in the
# text. * `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = ['gvim', '-geometry', '500x3', '-f', '{file}', '-c', 'normal {line}G{column0}l']

# Font family for cursive fonts.
# Type: FontFamily
c.fonts.web.family.cursive = None

# Timeout (in milliseconds) for partially typed key bindings. If the
# current input forms only partial matches, the keystring will be
# cleared after this time.
# Type: Int
c.input.partial_timeout = 5000

# Turn on Qt HighDPI scaling. This is equivalent to setting
# QT_AUTO_SCREEN_SCALE_FACTOR=1 in the environment. It's off by default
# as it can cause issues with some bitmap fonts. As an alternative to
# this, it's possible to set font sizes and the `zoom.default` setting.
# Type: Bool
c.qt.highdpi = False

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'bottom'

c.fonts.completion.entry = '11pt monospace'
c.fonts.completion.category = '11pt monospace'
c.fonts.statusbar = '10pt monospace'
c.fonts.tabs = '10pt DejaVuSans Nerd Font'
c.fonts.hints = '11pt DejaVuSans Nerd Font'

# Bindings for normal mode
config.bind(',a', 'hint links spawn mpv --no-video --ytdl-format 140 {hint-url} ')
config.bind(',d', 'spawn --userscript dict')
config.bind(',e', 'spawn --userscript exec')
config.bind(',r', 'spawn --userscript readability')
config.bind(',v', 'hint links spawn mpv --ytdl-format 18 {hint-url}')
config.bind('<F2>', 'set-cmd-text -s :open -t')
config.bind('<Shift-F2>', 'set-cmd-text -s :open')
config.bind('<F9>', 'scroll-page 0 1')
config.bind('<F10>', 'scroll-page 0 -1')
config.bind('<Shift-F9>', 'scroll down')
config.bind('<Shift-F10>', 'scroll up')
config.bind('j', 'scroll-page 0 1')
config.bind('k', 'scroll-page 0 -1')
config.bind('J', 'scroll down')
config.bind('K', 'scroll up')
config.bind('x', 'tab-close')
config.bind('d', 'tab-prev')
config.bind('s', 'tab-next')
config.bind('f', 'hint all')
config.bind('o', 'set-cmd-text -s :open -t')
config.bind('O', 'set-cmd-text -s :open')
